In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
# load the standard dataset from the scikit-learn

In [3]:
from sklearn.datasets import load_iris
iris=load_iris()

In [4]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
# convert the dataset into the pandas dataframe

In [6]:
iris_data=pd.DataFrame(iris.data,columns=["sepal length","sepal width","petal length","petal width"])
iris_data["category"]=iris.target
iris_data

sepal length  sepal width  petal length  petal width  category
0             5.1          3.5           1.4          0.2         0
1             4.9          3.0           1.4          0.2         0
2             4.7          3.2           1.3          0.2         0
3             4.6          3.1           1.5          0.2         0
4             5.0          3.6           1.4          0.2         0
..            ...          ...           ...          ...       ...
145           6.7          3.0           5.2          2.3         2
146           6.3          2.5           5.0          1.9         2
147           6.5          3.0           5.2          2.0         2
148           6.2          3.4           5.4          2.3         2
149           5.9          3.0           5.1          1.8         2

[150 rows x 5 columns]

In [7]:
iris_data.columns.values

array(['sepal length', 'sepal width', 'petal length', 'petal width',
       'category'], dtype=object)

In [8]:
new_columns=['category','sepal length', 'sepal width', 'petal length', 'petal width']
iris_data=iris_data[new_columns]
iris_data

category  sepal length  sepal width  petal length  petal width
0           0           5.1          3.5           1.4          0.2
1           0           4.9          3.0           1.4          0.2
2           0           4.7          3.2           1.3          0.2
3           0           4.6          3.1           1.5          0.2
4           0           5.0          3.6           1.4          0.2
..        ...           ...          ...           ...          ...
145         2           6.7          3.0           5.2          2.3
146         2           6.3          2.5           5.0          1.9
147         2           6.5          3.0           5.2          2.0
148         2           6.2          3.4           5.4          2.3
149         2           5.9          3.0           5.1          1.8

[150 rows x 5 columns]

In [9]:
iris_data.isnull().sum()

category        0
sepal length    0
sepal width     0
petal length    0
petal width     0
dtype: int64

In [10]:
# Apply the XGBoost to train the models and make predictions

In [11]:
x=iris_data.drop(["category"],axis=1)
y=iris_data["category"]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=365)

In [14]:
import xgboost as xgb

In [15]:
train=xgb.DMatrix(x_train,label=y_train)
test=xgb.DMatrix(x_test,label=y_test)

In [16]:
param01={"max_depth":4,
       "eta":0.1,
       "objective": "multi:softmax",
       "num_class":3}
epochs01=10

In [17]:
model01=xgb.train(param01,train,epochs01)

[22:48:35] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softmax' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [18]:
param02={"max_depth":4,
       "eta":0.1,
       "objective": "multi:softprob",
       "num_class":3}
epochs01=10

In [19]:
model02=xgb.train(param02,train,epochs01)

[22:48:35] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [20]:
prediction01=model01.predict(test)
prediction01

array([0., 0., 0., 0., 0., 0., 2., 1., 2., 1., 1., 1., 1., 0., 1., 2., 2.,
       2., 0., 1., 1., 2., 1., 2., 2., 2., 2., 0., 1., 1.], dtype=float32)

In [21]:
prediction02_prob=model02.predict(test)
prediction02_prob

array([[0.7088106 , 0.14685647, 0.14433293],
       [0.7088106 , 0.14685647, 0.14433293],
       [0.7088106 , 0.14685647, 0.14433293],
       [0.7088106 , 0.14685647, 0.14433293],
       [0.7088106 , 0.14685647, 0.14433293],
       [0.7088106 , 0.14685647, 0.14433293],
       [0.14460628, 0.14907564, 0.7063181 ],
       [0.1306504 , 0.64525265, 0.224097  ],
       [0.14460628, 0.14907564, 0.7063181 ],
       [0.14403138, 0.7113382 , 0.1446304 ],
       [0.14403138, 0.7113382 , 0.1446304 ],
       [0.14403138, 0.7113382 , 0.1446304 ],
       [0.14403138, 0.7113382 , 0.1446304 ],
       [0.7088106 , 0.14685647, 0.14433293],
       [0.14403138, 0.7113382 , 0.1446304 ],
       [0.14460628, 0.14907564, 0.7063181 ],
       [0.14460628, 0.14907564, 0.7063181 ],
       [0.14460628, 0.14907564, 0.7063181 ],
       [0.7088106 , 0.14685647, 0.14433293],
       [0.14403138, 0.7113382 , 0.1446304 ],
       [0.14403138, 0.7113382 , 0.1446304 ],
       [0.15119499, 0.155868  , 0.692937  ],
       [0.

In [22]:
prediction02=np.asarray([np.argmax(i) for i in prediction02_prob])
prediction02

array([0, 0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 1, 1, 0, 1, 2, 2, 2, 0, 1, 1, 2,
       1, 2, 2, 2, 2, 0, 1, 1], dtype=int64)

In [23]:
# check the efficiency of the models

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
score01=accuracy_score(y_test,prediction01)
score02=accuracy_score(y_test,prediction02)

In [26]:
print(score01)
print(score02)

1.0
1.0
